### ISSUE TITLE
Add support for the new print() function

### ISSUE THREAD

**Issue by maxsmythe** [open-policy-agent/frameworks#149]
Taken from:

https://github.com/open-policy-agent/gatekeeper/issues/1654

from @tsandall 

In v0.34.0 we added a new print() function that helps with simple debugging use cases. Library embeddings have to be updated to capture print() output. Without opt-in, print() statements are just erased from the policy at compile-time. Note, print() enablement might be better solved in the constraint framework. Feel free to close and move the issue over to constraints if you want.

Conftest was recently updated to support print(). See this PR: open-policy-agent/conftest#629

For more info on the print() function see this blog post: https://blog.openpolicyagent.org/introducing-the-opa-print-function-809da6a13aee

----

from @maxsmythe 

Nice!

QQ about print: is it still subject to indexing (as in a rule that is not called because of indexing would lead to print not being called), or is it always called?

This definitely sounds like something that should go into the constraint framework.

@willbeason FYI

Closing this and re-opening there.

**Comment by willbeason** [comment]
Done - print is explicitly enableable in #202
