### ISSUE TITLE
Add client.AddTemplate benchmarks

### ISSUE THREAD

**Issue by willbeason** [open-policy-agent/frameworks#151]
Add two benchmarks for compiling ConstraintTemplate: one simple template, and one complex template.

For the simple CT (and the general benchmarking code), I recommend looking at [this code](https://github.com/open-policy-agent/frameworks/blob/41b132b04e0cd0cafe0e5fb344e9723db532d610/constraint/pkg/client/client_benchmark_test.go). See `BenchmarkClient_AddTemplate` and `makeModule`.

For the simple CT, we're trying to find the answer to the question of "What is the largest number of CTs a user could possibly have?"

For the complex CT, find a reasonably complex one from the [gatekeeper-library](https://github.com/open-policy-agent/gatekeeper-library). It doesn't particularly matter which one - so long as it looks complex. The idea is to answer the question "What is the largest number of normal CTs a user can have?"

It'd be best for this to live in its own test file - maybe `addtemplate_benchmark_test.go`?

**Comment by maxsmythe** [comment]
Here is the most complex CT I'm aware of:

https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/containerlimits/template.yaml
