### ISSUE TITLE
Increase unit test coverage for constraint/pkg/regorewriter

### ISSUE THREAD

**Issue by willbeason** [open-policy-agent/frameworks#157]
Coverage is ~60% and there's a lot of code execution paths which look easy to test but don't have tests yet.

Add tests for these.

**Comment by willbeason** [comment]
To test coverage:

`go test ./pkg/regorewriter --coverprofile=cover.out`

to see coverage line-by-line:

`go tool cover -html=cover.out`

**Comment by becky-hd** [comment]
+1

**Comment by willbeason** [comment]
Done!
