### ISSUE TITLE
Use string constants consistently

### ISSUE THREAD

**Issue by willbeason** [open-policy-agent/frameworks#163]
Strings like the following should live in their canonical locations in kubernetes packages:

```
"v1alpha1"
"v1beta1"
"constraints.gatekeeper.sh"
```

This aids discoverability, makes testing easier, and ensures that differences in manually-typed strings are impossible.

**Comment by willbeason** [comment]
`goconst` is a great tool for discovering these. Don't worry about getting every instance - just the ones that make sense/are important to flow.

```
go get github.com/jgautheron/goconst/cmd/goconst

goconst pkg/... -ignore "_test.go"
```

**Comment by willbeason** [comment]
The ones I've found are:

- "v1"
- "v1alpha1"
- "v1beta1"
- "constraints.gatekeeper.sh"
- "templates.gatekeeper.sh"
- "externaldata.gatekeeper.sh"

For the `/api/` locations, the appropriate place is in a declaration like:

```
	SchemeGroupVersion = schema.GroupVersion{Group: "externaldata.gatekeeper.sh", Version: "v1alpha1"}
```

In some cases, we define a constant but the code doesn't use it. For example "ProviderRequest" has a definition in `constraint/pkg/externaldata/request.go` but it isn't referenced in the same file.

"data.lib" and "data.inventory" aren't repeated a bunch of times, but they're so important we should have them as constants so it's clear that their repetition in both "main.go" and "client.go" is meaningful and can't accidentally be broken.

That's everything I could find. There might be more (feel free to look if you want).

**Comment by willbeason** [comment]
Also "data" since we define it as the root object users reference, so it pops up in a bunch of locations.

**Comment by maxsmythe** [comment]
Is this a blocker for sharding?

**Comment by becky-hd** [comment]
Moving constants to pkg/apis seems reasonable

**Comment by willbeason** [comment]
Mostly done as parts of various PRs.
