### ISSUE TITLE
[local.Driver] Copy Constraint matching library from gatekeeper to frameworks

### ISSUE THREAD

**Issue by willbeason** [open-policy-agent/frameworks#175]
In short: We want to Driver to have access to the logic we currently use in gatekeeper for matching objects to mutators. Much of this logic already exists in gatekeeper, so really it just needs to be migrated to frameworks.

This code should probably live in its own package, `pkg/client/match`.

Files to copy:
-  gatekeeper`pkg/mutation/match/match.go` -> frameworks `pkg/client/match/match.go`
- gatekeeper `pkg/util/prefix_wildcard.go` -> frameworks `pkg/client/match/prefix_wildcard.go` (don't put this in a "util" library)

(and their respective tests)

It's probably best to do this as its own PR before any additional work, so it's obvious if we end up changing any of the matching logic.

**Comment by maxsmythe** [comment]
We probably only want to copy the interface, since frameworks should be target-neutral

**Comment by willbeason** [comment]
Done since we've done the interface. The corresponding work in Gatekeeper has an issue there.
