### ISSUE TITLE
Library templates should use Rego methods, not string substitution

### ISSUE THREAD

**Issue by maxsmythe** [open-policy-agent/frameworks#61]
This code:

```
		if err := libTempl.Execute(libBuf, map[string]string{
			"ConstraintsRoot": fmt.Sprintf(`data.constraints["%s"].cluster["%s"]`, t.GetName(), constraintGroup),
			"DataRoot":        fmt.Sprintf(`data.external["%s"]`, t.GetName()),
		}); err != nil {
			return err
		}
```

Should be unnecessary. It would be nice if we could use strings of un-modified Rego and access various roots via import statements and/or helper functions.

This would make it easier to build and test TargetHandler library code while still abstracting away the root of the `constraint` and `data` trees.

**Comment by willbeason** [comment]
We no longer use string substitution for this, via #202
