### ISSUE TITLE
Properly handle OpenAPISpec Default values

### ISSUE THREAD

**Issue by briantkennedy** [open-policy-agent/frameworks#70]
If someone puts a default value in the OpenAPISpec for a ConstraintTemplate, this results in an error.  The ConstraintFramework should handle populating the default if present.

**Comment by acpana** [comment]
I'm not sure this is still the case today, but no errors are returned when attempting to use `default`s w OpenAPIV3 schema for a `ConstraintTemplate`.

**Comment by acpana** [comment]
I'm sure the ask is the same: make `default` params work but just in case I filed another issue: https://github.com/open-policy-agent/frameworks/issues/326
