### ISSUE TITLE
Support bulk load with AddTemplates

### ISSUE THREAD

**Issue by ritazh** [open-policy-agent/frameworks#91]
This should help with #79

**Comment by willbeason** [comment]
Made obsolete with #202 - there is no performance difference between "bulk load" and a bunch of sequential adds.

We could theoretically make things faster through parallel compilation, but in practice the gains here would be negligible (for Gatekeeper, but possibly non-negligible to other consumers of frameworks) compared to the time for the API Server to respond to creating and watching new types.
